--PROCEDIMIENTOS ALMACENADOS

USE CLINICA_SALUD;

--*****************************CONSULTORIO****************************************

--INSERTARCONSULTORIO
CREATE PROCEDURE sp_InsertarConsultorio
	@param_NumeroPiso INT = NULL
AS
BEGIN
	INSERT INTO CONSULTORIO
	(
		NUM_PISO
	)
	VALUES
	(
		@param_NumeroPiso
	)
END
GO

--QUITARCONSULTORIOENTODO
CREATE PROCEDURE sp_QuitarConsultorioEnTodo
	@param_IdConsultorio INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM CONSULTORIO WHERE ID_CONSULTORIO = @param_IdConsultorio)
	BEGIN
		DELETE CONSULTORIO_PACIENTE
		WHERE FK_CONSULTORIO= @param_IdConsultorio
	END
END
GO

--ELIMINARCONSULTORIO
CREATE PROCEDURE sp_EliminarConsultorio
	@param_Id INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM CONSULTORIO WHERE ID_CONSULTORIO = @param_Id)
	BEGIN   
		EXEC sp_QuitarConsultorioEnTodo
			@param_Id
		DELETE CONSULTORIO
		WHERE ID_CONSULTORIO = @param_Id
	END
END
GO

--ACTUALIZARCONSULTORIO
CREATE PROCEDURE sp_ActualizarConsultorio
	@param_IdConsultorio INT = NULL,
	@param_NumeroPiso INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM CONSULTORIO WHERE ID_CONSULTORIO = @param_IdConsultorio)
	BEGIN
		UPDATE CONSULTORIO
		SET NUM_PISO = @param_NumeroPiso
		WHERE ID_CONSULTORIO = @param_IdConsultorio
	END
END
GO

--OBTENERCONSULTORIOS
CREATE PROCEDURE sp_ObtenerConsultorios
AS
BEGIN
	SELECT * FROM CONSULTORIO
END
GO

--ASIGNARCONSULTORIO
CREATE PROCEDURE sp_AsignarConsultorio
	@param_IdConsultorio INT = NULL,
	@param_IdPaciente INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM PACIENTE WHERE ID_PACIENTE = @param_IdPaciente) AND
	EXISTS(SELECT * FROM CONSULTORIO WHERE ID_CONSULTORIO = @param_IdConsultorio)
	BEGIN
		INSERT INTO CONSULTORIO_PACIENTE
		(
			FK_CONSULTORIO,
			FK_PACIENTE
		)
		VALUES 
		(
			@param_IdConsultorio,
			@param_IdPaciente
		)
	END
END
GO

SELECT 
	*
FROM PACIENTE P 
JOIN CONSULTORIO_PACIENTE CP
	ON CP.FK_PACIENTE = P.ID_PACIENTE 
		JOIN CONSULTORIO C
			ON C.ID_CONSULTORIO = CP.FK_CONSULTORIO

--QUITARCONSULTORIO
CREATE PROCEDURE sp_QuitarConsultorio
	@param_IdConsultorio INT = NULL,
	@param_IdPaciente INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM PACIENTE WHERE ID_PACIENTE = @param_IdPaciente) AND
	EXISTS(SELECT * FROM CONSULTORIO WHERE ID_CONSULTORIO = @param_IdConsultorio)
	BEGIN
		DELETE CONSULTORIO_PACIENTE
		WHERE FK_PACIENTE = @param_IdPaciente AND FK_CONSULTORIO = @param_IdConsultorio
	END
END
GO

SELECT 
	*
FROM PACIENTE P 
JOIN CONSULTORIO_PACIENTE CP
	ON CP.FK_PACIENTE = P.ID_PACIENTE 
		JOIN CONSULTORIO C
			ON C.ID_CONSULTORIO = CP.FK_CONSULTORIO

--*****************************PERSONA****************************************

--INSERTARPERSONA
CREATE PROCEDURE sp_InsertarPersona
	@param_Cedula INT = NULL,
	@param_Nombre VARCHAR(20) = NULL
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM PERSONA WHERE CEDULA = @param_Cedula)
	BEGIN         
		INSERT INTO PERSONA
		(
			CEDULA,
			NOMBRE
		)
		VALUES
		(
			@param_Cedula,
			@param_Nombre
		)
	END
END
GO

SELECT * FROM PERSONA

--ELIMINARPERSONA
CREATE PROCEDURE sp_EliminarPersona
	@param_Cedula INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM PERSONA WHERE CEDULA = @param_Cedula)
	BEGIN
		DELETE PERSONA
		WHERE CEDULA = @param_Cedula
	END
END
GO

SELECT * FROM PERSONA

--ACTUALIZARPERSONA
CREATE PROCEDURE sp_ActualizarPersona
	@param_Cedula INT = NULL,
	@param_Nombre VARCHAR(20) = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM PERSONA WHERE CEDULA = @param_Cedula)
	BEGIN
		UPDATE PERSONA
		SET NOMBRE = @param_Nombre
		WHERE CEDULA = @param_Cedula
	END
END
GO

SELECT * FROM PERSONA

--OBTENERPERSONAS
CREATE PROCEDURE sp_ObtenerPersonas
AS
BEGIN
	SELECT * FROM PERSONA
END
GO

--*****************************ESPECIALIDAD****************************************

--INSERTARESPECIALIDAD
CREATE PROCEDURE sp_InsertarEspecialidad
	@param_Nombre VARCHAR(30) = NULL
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM ESPECIALIDAD WHERE NOMBRE = @param_Nombre)
	BEGIN   
		INSERT INTO ESPECIALIDAD
		(
			NOMBRE
		)
		VALUES
		(
			@param_Nombre
		)
	END
END
GO

EXEC sp_InsertarEspecialidad
	'Cardiología'
	--'Neurología'
	--'Pediatría'
	--'Otorrinolaringología'
	--'Nutrición'
	--'Geriatría'

SELECT * FROM ESPECIALIDAD

--QUITARESPECIALIDADENTODO
CREATE PROCEDURE sp_QuitarEspecialidadEnTodo
	@param_IdEspecialidad INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM ESPECIALIDAD WHERE ID_ESPECIALIDAD = @param_IdEspecialidad)
	BEGIN
		DELETE MEDICO_ESPECIALIDAD
		WHERE FK_ESPECIALIDAD = @param_IdEspecialidad
	END
END
GO

--ELIMINARESPECIALIDAD
CREATE PROCEDURE sp_EliminarEspecialidad
	@param_Id INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM ESPECIALIDAD WHERE ID_ESPECIALIDAD = @param_Id)
	BEGIN   
		EXEC sp_QuitarEspecialidadEnTodo
			@param_Id
		DELETE ESPECIALIDAD
		WHERE ID_ESPECIALIDAD = @param_Id
	END
END
GO

SELECT * FROM ESPECIALIDAD

--ACTUALIZARESPECIALIDAD
CREATE PROCEDURE sp_ActualizarEspecialidad
	@param_Id INT = NULL,
	@param_Nombre VARCHAR(30) = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM ESPECIALIDAD WHERE ID_ESPECIALIDAD = @param_Id)
	BEGIN   
		UPDATE ESPECIALIDAD
		SET NOMBRE = @param_Nombre
		WHERE ID_ESPECIALIDAD = @param_Id
	END
END
GO

SELECT * FROM ESPECIALIDAD

--OBTENERESPECIALIDADES
CREATE PROCEDURE sp_ObtenerEspecialidades
AS
BEGIN
	SELECT * FROM ESPECIALIDAD
END
GO

--ASIGNARESPECIALIDAD
CREATE PROCEDURE sp_AsignarEspecialidad
	@param_IdEspecialidad INT = NULL,
	@param_IdMedico INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM MEDICO WHERE ID_MEDICO = @param_IdMedico) AND
	EXISTS(SELECT * FROM ESPECIALIDAD WHERE ID_ESPECIALIDAD = @param_IdEspecialidad)
	BEGIN
		INSERT INTO MEDICO_ESPECIALIDAD
		(
			FK_MEDICO,
			FK_ESPECIALIDAD
		)
		VALUES 
		(
			@param_IdMedico,
			@param_IdEspecialidad
		)
	END
END
GO

SELECT 
	M.ID_MEDICO,
	M.FK_CEDULA,
	E.ID_ESPECIALIDAD,
	E.NOMBRE
FROM MEDICO M 
JOIN MEDICO_ESPECIALIDAD ME 
	ON ME.FK_MEDICO = M.ID_MEDICO 
		JOIN ESPECIALIDAD E 
			ON E.ID_ESPECIALIDAD = ME.FK_ESPECIALIDAD

--QUITARESPECIALIDAD
CREATE PROCEDURE sp_QuitarEspecialidad
	@param_IdEspecialidad INT = NULL,
	@param_IdMedico INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM MEDICO WHERE ID_MEDICO = @param_IdMedico) AND
	EXISTS(SELECT * FROM ESPECIALIDAD WHERE ID_ESPECIALIDAD = @param_IdEspecialidad)
	BEGIN
		DELETE MEDICO_ESPECIALIDAD
		WHERE FK_MEDICO = @param_IdMedico AND FK_ESPECIALIDAD = @param_IdEspecialidad
	END
END
GO

--*****************************MEDICO****************************************

--INSERTARMEDICO
CREATE PROCEDURE sp_InsertarMedico
	@param_Cedula INT = NULL,
	@param_Nombre VARCHAR(20) = NULL,
	@param_Consultorio INT = NULL,
	@param_Especialidad INT = NULL
	
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM PERSONA WHERE CEDULA = @param_Cedula)
	BEGIN   
		EXEC sp_InsertarPersona
			@param_Cedula,
			@param_Nombre
	END
	IF EXISTS(SELECT * FROM PERSONA WHERE CEDULA = @param_Cedula AND NOMBRE = @param_Nombre)
	BEGIN 
		INSERT INTO MEDICO
		(
			FK_CEDULA,
			FK_ID_CONSULTORIO
		)
		VALUES
		(
			@param_Cedula,
			@param_Consultorio
		)

		DECLARE @Id_Medico INT = (SELECT ID_MEDICO FROM MEDICO WHERE FK_CEDULA = @param_Cedula)

		EXEC sp_AsignarEspecialidad
			@param_Especialidad,
			@Id_Medico
	END
END
GO

SELECT 
	M.ID_MEDICO,
	M.FK_CEDULA,
	E.ID_ESPECIALIDAD,
	E.NOMBRE
FROM MEDICO M 
JOIN MEDICO_ESPECIALIDAD ME 
	ON ME.FK_MEDICO = M.ID_MEDICO 
		JOIN ESPECIALIDAD E 
			ON E.ID_ESPECIALIDAD = ME.FK_ESPECIALIDAD

--ELIMINARMEDICO
CREATE PROCEDURE sp_EliminarMedico
	@param_IdMedico INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM MEDICO WHERE ID_MEDICO = @param_IdMedico)
	BEGIN
		DECLARE @Cedula INT = (SELECT FK_CEDULA FROM MEDICO WHERE ID_MEDICO = @param_IdMedico)

		DELETE MEDICO_ESPECIALIDAD
		WHERE FK_MEDICO = @param_IdMedico

		DELETE MEDICO
		WHERE ID_MEDICO = @param_IdMedico

		EXEC sp_EliminarPersona
			@Cedula
	END
END
GO

SELECT * FROM PERSONA
SELECT * FROM MEDICO
SELECT * FROM MEDICO_ESPECIALIDAD

--ACTUALIZARMEDICO
CREATE PROCEDURE sp_ActualizarMedico
	@param_IdMedico INT = NULL,
	@param_Nombre VARCHAR(20) = NULL,
	@param_Consultorio INT = NULL,
	@param_Especialidad INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM MEDICO WHERE ID_MEDICO = @param_IdMedico)
	BEGIN
		DECLARE @Cedula INT = (SELECT FK_CEDULA FROM MEDICO WHERE ID_MEDICO = @param_IdMedico)

		EXEC sp_ActualizarPersona
			@Cedula,
			@param_Nombre

		UPDATE MEDICO 
		SET FK_ID_CONSULTORIO = @param_Consultorio
		WHERE ID_MEDICO = @param_IdMedico

		DELETE MEDICO_ESPECIALIDAD
		WHERE FK_MEDICO = @param_IdMedico

		EXEC sp_AsignarEspecialidad
			@param_Especialidad,
			@param_IdMedico
	END
END
GO

SELECT 
	*
FROM MEDICO M 
JOIN MEDICO_ESPECIALIDAD ME 
	ON ME.FK_MEDICO = M.ID_MEDICO 
		JOIN ESPECIALIDAD E 
			ON E.ID_ESPECIALIDAD = ME.FK_ESPECIALIDAD
				JOIN PERSONA P
					ON P.CEDULA = M.FK_CEDULA

--OBTENERMEDICOS
CREATE PROCEDURE sp_ObtenerMedicos
AS
BEGIN
	SELECT 
		P.CEDULA,
		P.NOMBRE,
		M.ID_MEDICO,
		E.NOMBRE AS ESPECIALIDAD,
		M.FK_ID_CONSULTORIO AS NUMERO_CONSULTORIO
	FROM MEDICO M 
	JOIN MEDICO_ESPECIALIDAD ME 
		ON ME.FK_MEDICO = M.ID_MEDICO 
			JOIN ESPECIALIDAD E 
				ON E.ID_ESPECIALIDAD = ME.FK_ESPECIALIDAD
					JOIN PERSONA P
						ON P.CEDULA = M.FK_CEDULA
END
GO

--*****************************ENFERMEDAD****************************************

--INSERTARENFERMEDAD
CREATE PROCEDURE sp_InsertarEnfermedad
	@param_Nombre VARCHAR(30) = NULL
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM ENFERMEDAD WHERE NOMBRE = @param_Nombre)
	BEGIN   
		INSERT INTO ENFERMEDAD
		(
			NOMBRE
		)
		VALUES
		(
			@param_Nombre
		)
	END
END
GO

EXEC sp_InsertarEnfermedad
	'Asma'
	--'Artritis'
	--'Clamidia'
	--'Ébola'
	--'Diabetes'
	--'Epilepsia'

SELECT * FROM ENFERMEDAD

--QUITARENFERMEDADENTODO
CREATE PROCEDURE sp_QuitarEnfermedadEnTodo
	@param_IdEnfermedad INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM ENFERMEDAD WHERE ID_ENFERMEDAD = @param_IdEnfermedad)
	BEGIN
		DELETE PACIENTE_ENFERMEDAD
		WHERE FK_ID_ENFERMEDAD = @param_IdEnfermedad
	END
END
GO

--ELIMINARENFERMEDAD
CREATE PROCEDURE sp_EliminarEnfermedad
	@param_Id INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM ENFERMEDAD WHERE ID_ENFERMEDAD = @param_Id)
	BEGIN   
		EXEC sp_QuitarEnfermedadEnTodo
			@param_Id
		DELETE ENFERMEDAD
		WHERE ID_ENFERMEDAD= @param_Id
	END
END
GO

SELECT * FROM ENFERMEDAD

--ACTUALIZARENFERMEDAD
CREATE PROCEDURE sp_ActualizarEnfermedad
	@param_Id INT = NULL,
	@param_Nombre VARCHAR(30) = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM ENFERMEDAD WHERE ID_ENFERMEDAD = @param_Id)
	BEGIN   
		UPDATE ENFERMEDAD
		SET NOMBRE = @param_Nombre
		WHERE ID_ENFERMEDAD = @param_Id
	END
END
GO

SELECT * FROM ENFERMEDAD

--OBTENERENFERMEDADES
CREATE PROCEDURE sp_ObtenerEnfermedades
AS
BEGIN
	SELECT * FROM ENFERMEDAD
END
GO

EXEC sp_ObtenerEnfermedades

--ASIGNARENFERMEDAD
CREATE PROCEDURE sp_AsignarEnfermedad
	@param_IdEnfermedad INT = NULL,
	@param_IdPaciente INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM PACIENTE WHERE ID_PACIENTE = @param_IdPaciente) AND
	EXISTS(SELECT * FROM ENFERMEDAD WHERE ID_ENFERMEDAD = @param_IdEnfermedad)
	BEGIN
		INSERT INTO PACIENTE_ENFERMEDAD
		(
			FK_ID_PACIENTE,
			FK_ID_ENFERMEDAD
		)
		VALUES 
		(
			@param_IdPaciente,
			@param_IdEnfermedad
		)
	END
END
GO

SELECT 
	*
FROM PACIENTE P 
JOIN PACIENTE_ENFERMEDAD PE 
	ON PE.FK_ID_PACIENTE = P.ID_PACIENTE 
		JOIN ENFERMEDAD E 
			ON E.ID_ENFERMEDAD = PE.FK_ID_ENFERMEDAD

--QUITARENFERMEDAD
CREATE PROCEDURE sp_QuitarEnfermedad
	@param_IdEnfermedad INT = NULL,
	@param_IdPaciente INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM PACIENTE WHERE ID_PACIENTE = @param_IdPaciente) AND
	EXISTS(SELECT * FROM ENFERMEDAD WHERE ID_ENFERMEDAD = @param_IdEnfermedad)
	BEGIN
		DELETE PACIENTE_ENFERMEDAD
		WHERE FK_ID_PACIENTE = @param_IdPaciente AND FK_ID_ENFERMEDAD = @param_IdEnfermedad
	END
END
GO

SELECT 
	*
FROM PACIENTE P 
JOIN PACIENTE_ENFERMEDAD PE 
	ON PE.FK_ID_PACIENTE = P.ID_PACIENTE 
		JOIN ENFERMEDAD E 
			ON E.ID_ENFERMEDAD = PE.FK_ID_ENFERMEDAD

--*****************************PACIENTE****************************************

--INSERTARPACIENTE
CREATE PROCEDURE sp_InsertarPaciente
	@param_Cedula INT = NULL,
	@param_Nombre VARCHAR(20) = NULL,
	@param_Consultorio INT = NULL,
	@param_Enfermedad INT = NULL
	
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM PERSONA WHERE CEDULA = @param_Cedula)
	BEGIN   
		EXEC sp_InsertarPersona
			@param_Cedula,
			@param_Nombre
	END
	IF EXISTS(SELECT * FROM PERSONA WHERE CEDULA = @param_Cedula AND NOMBRE = @param_Nombre)
	BEGIN 
		INSERT INTO PACIENTE
		(
			FK_CEDULA_PACIENTE
		)
		VALUES
		(
			@param_Cedula
		)

		DECLARE @Id_Paciente INT = (SELECT ID_PACIENTE FROM PACIENTE WHERE FK_CEDULA_PACIENTE = @param_Cedula)

		EXEC sp_AsignarConsultorio
			@param_Consultorio,
			@Id_Paciente

		EXEC sp_AsignarEnfermedad
			@param_Enfermedad,
			@Id_Paciente
	END
END
GO

SELECT * FROM PERSONA
SELECT * FROM PACIENTE
SELECT * FROM PACIENTE_ENFERMEDAD
SELECT * FROM CONSULTORIO_PACIENTE


--ELIMINARPACIENTE
CREATE PROCEDURE sp_EliminarPaciente
	@param_IdPaciente INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM PACIENTE WHERE ID_PACIENTE = @param_IdPaciente)
	BEGIN
		DECLARE @Cedula INT = (SELECT FK_CEDULA_PACIENTE FROM PACIENTE WHERE ID_PACIENTE = @param_IdPaciente)

		DELETE CONSULTORIO_PACIENTE
		WHERE FK_PACIENTE = @param_IdPaciente

		DELETE PACIENTE_ENFERMEDAD
		WHERE FK_ID_PACIENTE = @param_IdPaciente

		DELETE PACIENTE
		WHERE ID_PACIENTE = @param_IdPaciente

		EXEC sp_EliminarPersona
			@Cedula
	END
END
GO

SELECT * FROM PERSONA
SELECT * FROM PACIENTE
SELECT * FROM CONSULTORIO_PACIENTE
SELECT * FROM PACIENTE_ENFERMEDAD

--ACTUALIZARPACIENTE
CREATE PROCEDURE sp_ActualizarPaciente
	@param_IdPaciente INT = NULL,
	@param_Nombre VARCHAR(20) = NULL,
	@param_Consultorio INT = NULL,
	@param_Enfermedad INT = NULL
AS
BEGIN
	IF EXISTS(SELECT * FROM PACIENTE WHERE ID_PACIENTE = @param_IdPaciente)
	BEGIN
		DECLARE @Cedula INT = (SELECT FK_CEDULA_PACIENTE FROM PACIENTE WHERE ID_PACIENTE = @param_IdPaciente)

		EXEC sp_ActualizarPersona
			@Cedula,
			@param_Nombre

		DELETE CONSULTORIO_PACIENTE
		WHERE FK_PACIENTE = @param_IdPaciente

		DELETE PACIENTE_ENFERMEDAD
		WHERE FK_ID_PACIENTE = @param_IdPaciente

		EXEC sp_AsignarConsultorio
			@param_Consultorio,
			@param_IdPaciente

		EXEC sp_AsignarEnfermedad
			@param_Enfermedad,
			@param_IdPaciente
	END
END
GO

SELECT * FROM PERSONA
SELECT * FROM PACIENTE
SELECT * FROM CONSULTORIO_PACIENTE
SELECT * FROM PACIENTE_ENFERMEDAD

--OBTENERPACIENTES
CREATE PROCEDURE sp_ObtenerPacientes
AS
BEGIN
	SELECT 
		P.ID_PACIENTE,
		PP.CEDULA,
		PP.NOMBRE,
		E.NOMBRE AS ENFERMEDAD,
		C.ID_CONSULTORIO AS NUM_CONSULTORIO,
		C.NUM_PISO
	FROM PACIENTE P
		JOIN PERSONA PP
			ON PP.CEDULA = P.FK_CEDULA_PACIENTE
				JOIN PACIENTE_ENFERMEDAD PE
					ON PE.FK_ID_PACIENTE = P.ID_PACIENTE
						JOIN ENFERMEDAD E
							ON E.ID_ENFERMEDAD = PE.FK_ID_ENFERMEDAD
								JOIN CONSULTORIO_PACIENTE CP
									ON CP.FK_PACIENTE = P.ID_PACIENTE
										JOIN CONSULTORIO C
											ON C.ID_CONSULTORIO = CP.FK_CONSULTORIO
END
GO

EXEC sp_ObtenerPacientes